apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/fluentd.pos
      tag kube.*
      format json
      read_from_head true
      time_key time
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>

    <match **>
      @type opensearch
      host opensearch
      port 9200
      scheme http
      logstash_format true
      include_tag_key true
      type_name fluentd
      logstash_prefix fluentd
    </match>