apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: opensearch
      namespace: logging
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: opensearch
      template:
        metadata:
          labels:
            app: opensearch
        spec:
          containers:
            - name: opensearch
              image: opensearchproject/opensearch:2.11.1
              env:
                - name: DISABLE_SECURITY_PLUGIN
                  value: "true"
              ports:
                - containerPort: 9200
  - apiVersion: v1
    kind: Service
    metadata:
      name: opensearch
      namespace: logging
    spec:
      selector:
        app: opensearch
      ports:
        - port: 9200